# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:11-jdk

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: gradle dependencies
      
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - restore_cache:
          keys:
            - v1-convertigo-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-convertigo-
            
      - run: gradle --info --stacktrace localBuild
      
      - store_artifacts:
          path: build/localBuild/MyFirstNGX_Android.apk
          destination: MyFirstNGX_Android.apk
      
      - save_cache:
          paths:
            - ~/convertigo
          key: v1-convertigo-{{ checksum "build.gradle" }}