# This is a basic workflow to help you get started with Actions

name: Convertigo CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Java
      uses: actions/setup-java@v1.3.0
      with:
        java-version: '11'

    - name: Echo env
      run: which gradle; env
    - name: Import iOS certificates
      uses: apple-actions/import-codesign-certs@v1
      with: 
        p12-file-base64: ${{ secrets.CERTIFICATES_P12 }}
        p12-password: ${{ secrets.CERTIFICATES_P12_PASSWORD }}
    - name: Import Mobile Provision
      run: |
        uuid=`grep UUID -A1 -a ConvertigoWildcard20200914.mobileprovision | grep -io "[-A-F0-9]\{36\}"`
        echo uuid $uuid
        cp ConvertigoWildcard20200914.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/$uuid.mobileprovision
    - name: Run Convertigo build
      run: echo "Build MyFirstNGX" && gradle --no-daemon --stacktrace --info localBuild -Pconvertigo.performsMobileBuild=false -Pconvertigo.load.mobileApplicationEndpoint=https://beta.convertigo.net/convertigo
    - name: Echo env bis
      run: |
        env
        pwd
        ls -lha build
        ls -lha build/*
    - name: Upload packages
      uses: actions/upload-artifact@v2
      with:
        name: Mobile Packages
        path: build/localBuild/* # or path/to/artifact 
