# This is a basic workflow to help you get started with Actions

name: Convertigo CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Java
      uses: actions/setup-java@v1.3.0
      with:
        java-version: '11'
    - name: Run Convertigo build
      run: |
        echo "Build MyFirstNGX"
        gradle --no-daemon --stacktrace --info localBuild \
          -Pconvertigo.performsMobileBuild=true 
    - name: Echo env bis
      run: |
        env
        pwd
        mkdir -p build
        ls -lha build
    - name: Upload Android packages
      uses: actions/upload-artifact@v2
      with:
        name: Android Packages
        path: build/localBuild/*.apk 
